/**
 * Token-usage normalization & formatting helpers.
 *
 * Every backend reports token usage differently (Ollama: `prompt_eval_count` /
 * `eval_count`; OpenAI-compatible: `usage.prompt_tokens` / `completion_tokens`;
 * Gemini: `usageMetadata`), and some report nothing at all. The clients map
 * their raw payloads into this single shape, which the chat page then renders
 * under the assistant answer:
 *
 *   { input, output, total, cached, estimated }
 *
 * `estimated` marks a value derived locally (character heuristic, see
 * TextProcessor.estimateTokens) instead of reported by the service — the UI
 * prefixes such numbers with "≈" so an approximation is never mistaken for a
 * real measurement.
 *
 * Zero dependencies on purpose: the Node self-check scripts import this module
 * directly (no browser stub needed).
 */

/**
 * Formats a count with thousands separators (locale-independent, so tests and
 * exported documents look the same everywhere).
 * @param {number} n - Number to format
 * @returns {string} e.g. "7,010"
 */
export function formatCount(n) {
  const v = Math.round(Number(n) || 0);
  return String(v).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

/**
 * Coerces a raw value into a non-negative integer, or null when unusable.
 * @param {*} value - Raw value
 * @returns {number|null}
 */
function num(value) {
  const n = Number(value);
  return Number.isFinite(n) && n >= 0 ? Math.round(n) : null;
}

/**
 * Builds the normalized usage object from already-extracted numbers.
 * @param {*} input - Input (prompt) tokens, may be null when unknown
 * @param {*} output - Output (completion) tokens, may be null when unknown
 * @param {Object} [extra] - { cached, total, estimated }
 * @returns {Object|null} Normalized usage, or null when nothing usable
 */
function build(input, output, extra = {}) {
  const i = num(input);
  const o = num(output);
  if (i == null && o == null) return null;

  const explicitTotal = num(extra.total);
  const total = explicitTotal != null
    ? explicitTotal
    : (i != null && o != null ? i + o : null);

  return {
    input: i ?? 0,
    output: o ?? 0,
    total,
    cached: num(extra.cached) ?? 0,
    estimated: Boolean(extra.estimated)
  };
}

/**
 * Normalizes an Ollama streaming part. The final part of a stream carries
 * `prompt_eval_count` / `eval_count` (and `done: true`).
 * @param {Object} part - One part of the Ollama stream
 * @returns {Object|null} Normalized usage
 */
export function normalizeOllamaUsage(part) {
  if (!part || typeof part !== 'object') return null;
  return build(part.prompt_eval_count, part.eval_count);
}

/**
 * Normalizes an OpenAI-compatible `usage` object. Handles the common provider
 * variations for cached tokens (OpenAI `prompt_tokens_details.cached_tokens`,
 * DeepSeek `prompt_cache_hit_tokens`, Moonshot/others `cached_tokens`).
 * @param {Object} raw - The `usage` field of a chat-completions payload
 * @returns {Object|null} Normalized usage
 */
export function normalizeOpenAIUsage(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const details = raw.prompt_tokens_details && typeof raw.prompt_tokens_details === 'object'
    ? raw.prompt_tokens_details
    : {};
  const cached = raw.prompt_cache_hit_tokens ?? details.cached_tokens ?? raw.cached_tokens;
  return build(raw.prompt_tokens, raw.completion_tokens, { cached, total: raw.total_tokens });
}

/**
 * Normalizes a Gemini `usageMetadata`. Reasoning tokens are folded into the
 * output number (they are generated by the model), while `total` is kept
 * exactly as reported by the API.
 * @param {Object} meta - `chunk.usageMetadata`
 * @returns {Object|null} Normalized usage
 */
export function normalizeGeminiUsage(meta) {
  if (!meta || typeof meta !== 'object') return null;
  const candidates = num(meta.candidatesTokenCount);
  const thoughts = num(meta.thoughtsTokenCount);
  const output = candidates == null && thoughts == null
    ? null
    : (candidates ?? 0) + (thoughts ?? 0);
  return build(meta.promptTokenCount, output, {
    cached: meta.cachedContentTokenCount,
    total: meta.totalTokenCount
  });
}

/**
 * Creates an estimated usage record (no number came back from the service).
 * @param {number} input - Estimated input tokens
 * @param {number} output - Estimated output tokens
 * @returns {Object|null} Normalized usage flagged as estimated
 */
export function makeEstimatedUsage(input, output) {
  return build(input, output, { estimated: true });
}

/**
 * Adds two usage records — used to accumulate the several requests a single
 * turn can make (one per tool-call round).
 * @param {Object|null} a - First usage
 * @param {Object|null} b - Second usage
 * @returns {Object|null} Combined usage
 */
export function mergeUsage(a, b) {
  if (!a) return b || null;
  if (!b) return a;
  const total = (a.total == null && b.total == null)
    ? null
    : (a.total || 0) + (b.total || 0);
  return {
    input: (a.input || 0) + (b.input || 0),
    output: (a.output || 0) + (b.output || 0),
    total,
    cached: (a.cached || 0) + (b.cached || 0),
    estimated: Boolean(a.estimated || b.estimated)
  };
}

/**
 * Whether a usage record carries anything worth displaying.
 * @param {Object|null} usage - Normalized usage
 * @returns {boolean}
 */
export function hasUsage(usage) {
  if (!usage) return false;
  return (usage.input || 0) > 0 || (usage.output || 0) > 0 || (usage.total || 0) > 0;
}

/**
 * Renders a usage record as one compact line, e.g.
 *   "Input 6,120 · Output 890 · Total 7,010 tokens"
 * Estimated numbers get a "≈" prefix; unknown sections are skipped (during
 * streaming only the output is known, so only that is shown).
 *
 * @param {Object|null} usage - Normalized usage
 * @param {Object} [labels] - Localized words { input, output, total, cached, tokens }
 * @param {Object} [options] - { includeTotal: boolean }
 * @returns {string} Display text ('' when there is nothing to show)
 */
export function formatUsage(usage, labels = {}, options = {}) {
  if (!hasUsage(usage)) return '';

  const t = {
    input: 'Input',
    output: 'Output',
    total: 'Total',
    cached: 'Cached',
    tokens: 'tokens',
    ...labels
  };
  const mark = (n) => (usage.estimated ? '≈' : '') + formatCount(n);

  const hasInput = (usage.input || 0) > 0;
  const hasOutput = (usage.output || 0) > 0;
  const parts = [];

  if (hasInput) parts.push(`${t.input} ${mark(usage.input)}`);
  if (hasOutput) parts.push(`${t.output} ${mark(usage.output)}`);
  if (options.includeTotal !== false && hasInput && hasOutput && usage.total != null) {
    parts.push(`${t.total} ${mark(usage.total)}`);
  }
  if ((usage.cached || 0) > 0) parts.push(`${t.cached} ${formatCount(usage.cached)}`);

  if (!parts.length) return '';
  return `${parts.join(' · ')} ${t.tokens}`;
}
